services:
  - type: web
    name: wizedia-backend
    env: python
    python:
      version: 3.10.13
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:${PORT} main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 8080
      - key: FLASK_APP
        value: main.py
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: PATH
        value: "$HOME/.cargo/bin:${{PATH}}"
      # Add your other environment variables here
      # - key: YOUR_ENV_VAR
      #   value: your-value
